config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # As a user I can list tasks
  # Add a new route to list task
  # add a controller action and its view
  # This action should fetch all tasks, and a view should loop over these to display them.
  get 'tasks', to: 'tasks#index'

  # As a user, I can add task
  # Get the form, then create the post
  get "tasks/new", to: "tasks#new"

  # As a user, I can view task details
  # show, by id
  get 'tasks/:id', to: 'tasks#show', as: :task
  post "tasks", to: "tasks#create"

  # As a user, I can edit task
  # Get and patch
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  # Delete
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :select_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to tasks_path(@task)
  end

  private

  def select_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mx-auto" style="width: 500px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<br>
<br>
<br>

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<br>
<br>
<br>

<h1> <strong> My Tasks </strong></h1>

<div class="d-flex flex-column bd-highlight mb-3">
  <ul class="list-group">
  <% @tasks.each do |task| %>
    <li class="listings list-group-item" >
    <input class="form-check-input me-1" type="checkbox" value="">
    <%= link_to task.title, task_path(task) %>
    <%= link_to "🗑️",
            task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
  </ul>
</div>

<%= link_to 'Create new task' , tasks_new_path, class: 'links'  %>

app/views/tasks/new.html.erb
<br>
<br>
<br>

<div>
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.submit %>
  <% end %>
</div>

<div class = mt-3>
  <%= link_to '<back' , tasks_path, class: 'links'  %>
</div>

app/views/tasks/show.html.erb
<br>
<br>
<br>

<h2><%= @task.title %></h2>
<p class = "text-box"><%= @task.details %></p>

<% if @task.completed %>
<p><input class="form-check-input me-1" type="checkbox" value="" checked> The task is completed</p>
<% else %>
<p><input class="form-check-input me-1" type="checkbox" value=""> The task is not complete</p>
<% end %>

<%= link_to '<back' , tasks_path, class: 'links'  %>
<%= link_to 'Edit a task' , edit_task_path, class: 'links'  %>